services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2022
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  odoo16:
    image: odoo:16
    user: root
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072"  # live chat
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2022
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./repos.yml:/etc/repos.yml:ro  # Montar o arquivo de repositórios como arquivo
    restart: always
    command: >
      /bin/bash -c "
      if ! command -v git-aggregator &> /dev/null; then
        echo 'Instalando git-aggregator...';
        pip3 install git-aggregator;
      fi;
      if [ -f /etc/repos.yml ]; then
        echo 'Atualizando repositórios listados em repos.yml...';
        git-aggregator /etc/repos.yml || echo 'Falha ao atualizar os repositórios';
      else
        echo 'repos.yml não encontrado, pulando atualização de repositórios';
      fi;
      echo 'Iniciando Odoo...';
      exec /entrypoint.sh odoo;
      "
